/* 
 * Links definition for JavaScript for Mohawk Students
 * By default, links will go on the first occurrence of each word in each chapter
 *  
 *  define longer phrases before shorter (e.g. "if statements" before "statements"]
 *  format: [phrase, address, (optional chapter/section number)]
 *  use singular terms - regular plurals are automatically computed
 *                       (e.g. d0g->dogs and class->classes but not query->queries
 */

var links = [
    ["404 file not found", "http://en.wikipedia.org/wiki/HTTP_404"],
    ["absolute positioning", "http://www.w3schools.com/css/css_positioning.asp"],
    ["access level", "http://en.wikipedia.org/wiki/Visibility_(computer_science)"],
    ["actionscript", "http://en.wikipedia.org/wiki/Actionscript"],
    ["ajax", "http://en.wikipedia.org/wiki/Ajax_(programming)"],
    ["anonymous function", "http://en.wikipedia.org/wiki/Anonymous_function"],
    ["api", "http://en.wikipedia.org/wiki/Application_programming_interface"],
    ["app cache", "http://www.w3schools.com/html/html5_app_cache.asp"],
    ["aptana studio", "http://www.aptana.com/"],
    ["argument", "https://en.wikipedia.org/wiki/Parameter_(computer_programming)"],
    ["array", "http://en.wikipedia.org/wiki/Array"],
    ["associative array", "http://en.wikipedia.org/wiki/Associative_array"],
    ["asynchronous", "https://en.wikipedia.org/wiki/Asynchronous_I/O"],
    ["asynchronous javascript and xml", "http://en.wikipedia.org/wiki/Ajax_(programming)"],
    ["attribute", "http://en.wikipedia.org/wiki/HTML_attribute"],
    ["boolean", "http://en.wikipedia.org/wiki/Boolean_data_type"],
    ["bounding box", "http://www.w3schools.com/css/css_boxmodel.asp"],
    ["box model", "http://www.w3schools.com/css/css_boxmodel.asp"],
    ["c programming language", "http://en.wikipedia.org/wiki/C_programming_language"],
    ["c syntax", "http://en.wikipedia.org/wiki/C_syntax"],
    ["cache manifest", "http://en.wikipedia.org/wiki/Cache_manifest_in_HTML5"],
    ["call", "http://en.wikipedia.org/wiki/Callable_unit", "5."],
    ["callback", "http://en.wikipedia.org/wiki/Callback_(computer_programming)"],
    ["camelcase", "http://en.wikipedia.org/wiki/Camel_case"],
    ["camelcasepropertynames", "http://en.wikipedia.org/wiki/Camel_case"],
    ["canvas", "http://en.wikipedia.org/wiki/Html5_canvas"],
    ["chaining", "http://en.wikipedia.org/wiki/Method_chaining"],
    ["chrome web store", "https://chrome.google.com/webstore/category/apps"],
    ["class", "https://en.wikipedia.org/wiki/Class_(computer_programming)", "1."],
    ["click here for turtle ideas", "https://www.google.ca/search?q=turtle+drawing"],
    ["client-server", "http://en.wikipedia.org/wiki/Client%E2%80%93server_model"],
    ["client-side", "http://en.wikipedia.org/wiki/Client-side"],
    ["compiled", "http://en.wikipedia.org/wiki/Compiler"],
    ["compiler", "http://en.wikipedia.org/wiki/Compiler"],
    ["contiguous", "http://en.wikipedia.org/wiki/Contiguity#Computer_science"],
    ["cookie", "http://en.wikipedia.org/wiki/HTTP_cookie"],
    ["creative commons", "http://search.creativecommons.org/"],
    ["cross-browser compatibility", "http://en.wikipedia.org/wiki/Cross-browser"],
    ["crowdsourced", "http://en.wikipedia.org/wiki/Crowdsourcing"],
    ["css", "http://en.wikipedia.org/wiki/Css", "1."],
    ["css rule", "http://www.w3schools.com/css/css_syntax.asp"],
    ["css selector", "http://www.w3schools.com/cssref/css_selectors.asp"],
    ["css style rule", "http://www.w3schools.com/css/css_syntax.asp"],
    ["css3", "http://en.wikipedia.org/wiki/Css#CSS_3"],
    ["csunix.mohawkcollege.ca", "https://csunix.mohawkcollege.ca"],
    ["ctv", "http://www.ctv.ca"],
    ["data type", "http://en.wikipedia.org/wiki/Data_type"],
    ["declaration", "http://en.wikipedia.org/wiki/Declaration_(computer_programming)"],
    ["declare", "http://en.wikipedia.org/wiki/Declaration_(computer_programming)"],
    ["Document Object Model", "http://en.wikipedia.org/wiki/Document_Object_Model"],
    ["DOM", "http://en.wikipedia.org/wiki/Document_Object_Model"],
    ["DOM events", "http://www.w3schools.com/jsref/dom_obj_event.asp"],
    ["dynamic html", "http://en.wikipedia.org/wiki/Dhtml"],
    ["dynamically-typed", "http://en.wikipedia.org/wiki/Type_system"],
    ["eclipse", "https://www.eclipse.org/"],
    ["ecmascript", "http://en.wikipedia.org/wiki/Ecmascript"],
    ["element", "http://en.wikipedia.org/wiki/Html_element"],
    ["element object", "http://www.w3schools.com/jsref/dom_obj_all.asp"],
    ["escape character", "http://en.wikipedia.org/wiki/Escape_characters"],
    ["event", "http://en.wikipedia.org/wiki/Event_(computing)"],
    ["event listener", "http://en.wikipedia.org/wiki/Event_(computing)"],
    ["explicit typecasting", "http://en.wikipedia.org/wiki/Type_conversion"],
    ["extensible markup language", "https://en.wikipedia.org/wiki/Xml"],
    ["facebook", "http://www.facebook.com"],
    ["field", "http://en.wikipedia.org/wiki/Field_(computer_science)"],
    ["first-class function", "https://en.wikipedia.org/wiki/First-class_function"],
    ["flappy bird", "http://en.wikipedia.org/wiki/Flappy_Bird"],
    ["focus", "http://en.wikipedia.org/wiki/Focus_(computing)"],
    ["freesound.org", "http://freesound.org"],
    ["function", "http://en.wikipedia.org/wiki/Function_(computer_science)"],
    ["function literal", "http://en.wikipedia.org/wiki/Function_literal"],
    ["get and post", "http://www.w3schools.com/tags/ref_httpmethods.asp"],
    ["global", "http://en.wikipedia.org/wiki/Global_variable"],
    ["global ajax event handlers", "http://api.jquery.com/category/ajax/global-ajax-event-handlers"],
    ["global function", "http://www.w3schools.com/jsref/jsref_obj_global.asp"],
    ["global property", "http://www.w3schools.com/jsref/jsref_obj_global.asp"],
    ["global variable", "http://en.wikipedia.org/wiki/Global_variable"],
    ["google", "http://www.google.com"],
    ["google chrome", "https://www.google.com/intl/en_ca/chrome/browser/"],
    ["gradients", "http://www.w3schools.com/tags/canvas_createlineargradient.asp"],
    ["graphical user interface (gui)", "https://en.wikipedia.org/wiki/Graphical_user_interface"],
    ["hoisting", "http://www.sitepoint.com/back-to-basics-javascript-hoisting/"],
    ["html", "http://en.wikipedia.org/wiki/Html", "1."],
    ["html element", "http://en.wikipedia.org/wiki/Html_element"],
    ["html form", "http://www.w3schools.com/html/html_forms.asp"],
    ["html tag", "http://en.wikipedia.org/wiki/HTML_element"],
    ["html5", "http://en.wikipedia.org/wiki/HTML5"],
    ["HTML5 Form Attributes", "http://www.w3schools.com/html/html5_form_attributes.asp"],
    ["HTML5 Form Elements", "http://www.w3schools.com/html/html5_form_elements.asp"],
    ["HTML5 Input Types", "http://www.w3schools.com/html/html5_form_input_types.asp"],
    ["http", "http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol"],
    ["if statement", "http://en.wikipedia.org/wiki/If_statement"],
    ["image magnifier like this one", "http://mark-rolich.github.io/Magnifier.js/"],
    ["imperative", "http://en.wikipedia.org/wiki/Imperative_programming"],
    ["imperative programming", "http://en.wikipedia.org/wiki/Imperative_programming"],
    ["implicit typecasting", "http://en.wikipedia.org/wiki/Type_conversion"],
    ["integrated development environment", "http://en.wikipedia.org/wiki/Integrated_development_environment"],
    ["interpreted", "http://en.wikipedia.org/wiki/Interpreter_(computing)"],
    ["interpreter", "http://en.wikipedia.org/wiki/Interpreter_(computing)"],
    ["introduction to object-oriented javascript", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript"],
    ["java", "https://en.wikipedia.org/wiki/Java_(programming_language)"],
    ["JavaScript", "http://en.wikipedia.org/wiki/Javascript"],
    ["JavaScript Math object", "http://www.w3schools.com/js/js_math.asp"],
    ["javascript object notation", "http://en.wikipedia.org/wiki/JSON"],
    ["jesse james garrett", "http://www.adaptivepath.com/ideas/ajax-new-approach-web-applications"],
    ["jQuery", "http://en.wikipedia.org/wiki/Jquery"],
    ["jquery api", "http://api.jquery.com/"],
    ["jQuery API events reference", "http://api.jquery.com/category/events/"],
    ["jquery api selector reference", "http://api.jquery.com/category/selectors/"],
	["jQuery Manipulation API", "http://api.jquery.com/category/manipulation/"],
	["jQuery Traversal API", "http://api.jquery.com/category/traversing/"],
    ["jquery css classes", "http://www.w3schools.com/jquery/jquery_css_classes.asp"],
    ["jquery object", "http://learn.jquery.com/using-jquery-core/jquery-object/"],
    ["jquery selector", "http://www.w3schools.com/jquery/jquery_selectors.asp"],
    ["jQuery website", "http://jquery.com/"],
    ["JS Comparison Operators", "http://www.w3schools.com/js/js_comparisons.asp"],
    ["js data types", "http://www.w3schools.com/js/js_datatypes.asp"],
    ["JS Math", "http://www.w3schools.com/js/js_math.asp"],
    ["js popupalert", "http://www.w3schools.com/js/js_popup.asp"],
    ["JS String", "http://www.w3schools.com/js/js_strings.asp"],
    ["JS VAlidation", "http://www.w3schools.com/js/js_form_validation.asp"],
    ["jscript", "http://en.wikipedia.org/wiki/Jscript"],
    ["json", "http://en.wikipedia.org/wiki/JSON"],
    ["learn javascript", "http://www.w3schools.com/js/default.asp"],
    ["learn jquery", "http://learn.jquery.com/"],
    ["learn xml", "http://www.w3schools.com/xml/default.asp"],
    ["learn xml dom", "http://www.w3schools.com/dom/default.asp"],
    ["length of a line segment formula", "http://www.freemathhelp.com/length-line-segment.html"],
    ["let me know", "mailto:sam.scott1@mohawkcollege.ca"],
    ["literal", "https://en.wikipedia.org/wiki/Literal_(computer_programming)"],
    ["local", "http://en.wikipedia.org/wiki/Local_variable"],
    ["local variable", "http://en.wikipedia.org/wiki/Local_variable"],
    ["loop", "http://en.wikipedia.org/wiki/Control_flow#Loops"],
    ["markup language", "https://en.wikipedia.org/wiki/Markup_language"],
    ["media queries", "http://en.wikipedia.org/wiki/Media_queries"],
    ["method", "http://en.wikipedia.org/wiki/Method_(computer_programming)"],
    ["mime type", "http://en.wikipedia.org/wiki/Mime_types"],
    ["mohawk college", "http://mohawkcollege.ca"],
    ["mohawk college wikipedia page", "http://en.wikipedia.org/wiki/Mohawk_College"],
    ["Mozilla Developer Network ClassList", "https://developer.mozilla.org/en-US/docs/Web/API/Element.classList"],
    ["mozilla developer network keycode page", "https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent"],
    ["netbeans", "https://netbeans.org/"],
    ["netbeans connector plugin", "https://chrome.google.com/webstore/detail/netbeans-connector/hafdlehgocfcodbgjnpecfajgkeejnaa"],
    ["netscape", "http://en.wikipedia.org/wiki/Netscape"],
    ["node", "http://en.wikipedia.org/wiki/Node_(computer_science)"],
    ["node.js", "https://en.wikipedia.org/wiki/Node.js"],
    ["nodelist", "http://www.w3schools.com/dom/dom_nodelist.asp"],
    ["notepad++", "http://notepad-plus-plus.org/"],
    ["object", "http://en.wikipedia.org/wiki/Object_(computer_science)"],
    ["object literal", "http://en.wikipedia.org/wiki/Literal_(computer_programming)"],
    ["object-oriented", "http://en.wikipedia.org/wiki/Object-oriented_design"],
    ["onload event", "http://www.w3schools.com/jsref/event_onload.asp"],
    ["oracle", "http://en.wikipedia.org/wiki/Oracle_Corporation"],
    ["pac-man", "http://en.wikipedia.org/wiki/Pac-Man"],
    ["parse", "https://en.wikipedia.org/wiki/Parsing"],
    ["parsing", "https://en.wikipedia.org/wiki/Parsing"],
    ["patterns", "http://www.w3schools.com/tags/canvas_createpattern.asp"],
    ["php form handling", "http://www.w3schools.com/php/php_forms.asp"],
    ["pong", "http://en.wikipedia.org/wiki/Pong"],
    ["procedural programming", "https://en.wikipedia.org/wiki/Procedural_programming"],
    ["programming paradigm", "https://en.wikipedia.org/wiki/Programming_paradigm"],
    ["property", "https://en.wikipedia.org/wiki/Property_(computer_science)"],
    ["random", "http://en.wikipedia.org/wiki/Random_number_generation"],
    ["random numbers", "http://en.wikipedia.org/wiki/Random_number_generation"],
    ["reference", "http://en.wikipedia.org/wiki/Reference_(computer_science)"],
    ["return value", "http://en.wikipedia.org/wiki/Return_statement"],
    ["rollover", "http://en.wikipedia.org/wiki/Rollover_(web_design)"],
    ["same origin policy", "http://en.wikipedia.org/wiki/Same_origin_policy"],
    ["scope", "http://en.wikipedia.org/wiki/Scope_(computer_science)"],
    ["server side", "https://en.wikipedia.org/wiki/Server_side"],
    ["sheridan college", "http://www.sheridancollege.ca"],
    ["soundjay.com", "http://soundjay.com"],
    ["space invaders", "http://en.wikipedia.org/wiki/Space_invaders"],
    ["statement", "http://en.wikipedia.org/wiki/Statement_(computer_science)"],
    ["static", "http://en.wikipedia.org/wiki/Static_variable"],
    ["string", "http://en.wikipedia.org/wiki/String_(computer_science)"],
    ["string literal", "http://en.wikipedia.org/wiki/String_literal"],
    ["style sheet", "http://en.wikipedia.org/wiki/Style_sheet_(web_development)"],
    ["syntactically", "https://en.wikipedia.org/wiki/Syntax_(logic)"],
    ["syntax", "https://en.wikipedia.org/wiki/Syntax_(logic)"],
    ["syntax error", "http://en.wikipedia.org/wiki/Syntax_error"],
    ["table", "http://www.w3schools.com/html/html_tables.asp"],
    ["the boston globe", "http://www.bostonglobe.com"],
    ["this (keyword)", "http://en.wikipedia.org/wiki/This_(Java)"],
    ["traversal", "http://en.wikipedia.org/wiki/Tree_traversal"],
    ["traverse", "http://en.wikipedia.org/wiki/Tree_traversal"],
	["traversing", "http://en.wikipedia.org/wiki/Tree_traversal"],
    ["tree", "http://en.wikipedia.org/wiki/Tree_(data_structure)"],
    ["turing complete", "http://en.wikipedia.org/wiki/Turing_completeness"],
    ["Twitty Bird", "http://profsamscott.com/twittybird/"],
    ["value", "http://en.wikipedia.org/wiki/Value_(computer_science)"],
    ["variable", "http://en.wikipedia.org/wiki/Variable_(computer_science)"],
    ["variable scope", "http://en.wikipedia.org/wiki/Scope_(computer_science)"],
    ["w3fools", "http://www.w3fools.com/"],
    ["w3schools", "http://www.w3schools.com"],
    ["w3schools canvas reference", "http://www.w3schools.com/tags/ref_canvas.asp"],
    ["w3schools CSS :hover selector", "http://www.w3schools.com/cssref/sel_hover.asp"],
    ["w3schools CSS cursor property", "http://www.w3schools.com/cssref/pr_class_cursor.asp"],
    ["w3schools CSS Positioning", "http://www.w3schools.com/css/css_positioning.asp"],
    ["w3schools css selector reference", "http://www.w3schools.com/cssref/css_selectors.asp"],
    ["w3schools dom node reference", "http://www.w3schools.com/jsref/dom_obj_node.asp"],
    ["w3Schools event object reference", "http://www.w3schools.com/jsref/dom_obj_event.asp"],
    ["w3schools html events", "http://www.w3schools.com/tags/ref_eventattributes.asp"],
    ["w3schools HTML forms", "http://www.w3schools.com/html/html_forms.asp"],
    ["w3schools html5 application cache", "http://www.w3schools.com/html/html5_app_cache.asp"],
    ["w3schools learn ajax", "http://www.w3schools.com/ajax/"],
    ["w3schools learn jquery", "http://www.w3schools.com/jquery/default.asp"],
    ["wampserver", "http://www.apachefriends.org/en/xampp-windows.html"],
    ["weakly-typed", "http://en.wikipedia.org/wiki/Strong_and_weak_typing"],
    ["web app", "http://en.wikipedia.org/wiki/Web_application"],
    ["web application", "http://en.wikipedia.org/wiki/Web_application"],
    ["web storage", "http://en.wikipedia.org/wiki/Web_storage"],
    ["wikipedia", "https://www.wikipedia.org/"],
    ["window object", "http://www.w3schools.com/jsref/obj_window.asp"],
    ["wysiwyg", "http://en.wikipedia.org/wiki/WYSIWIG"],
    ["xampp", "http://www.apachefriends.org/en/xampp-windows.html"],
    ["xml", "https://en.wikipedia.org/wiki/Xml"],
    ["xmlhttprequest", "http://en.wikipedia.org/wiki/XMLHttpRequest"],
    ["yahoo query language", "http://developer.yahoo.com/yql/"],
    ["yql", "http://developer.yahoo.com/yql/"]
];

function sortlinksalpha(a, b) {
    if (a[0].toLowerCase() < b[0].toLowerCase())
        return -1;
    if (a[0].toLowerCase() > b[0].toLowerCase())
        return 1;
    console.log("WARNING: Duplicate links entry - " + a[0].toLowerCase());
    return 0
}

function sortlinkslength(a, b) {
    if (a[0].length !== b[0].length)
        return b[0].length - a[0].length;
    return b.length - a.length;
}
links.sort(sortlinkslength);
//links.sort(sortlinksalpha);
//console.log(JSON.stringify(links));